# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import llm_pb2 as llm__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMProxyServiceStub(object):
    """LLM 代理服务（适配 Azure OpenAI Chat Completions API）
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatCompletion = channel.unary_unary(
                '/llm.LLMProxyService/ChatCompletion',
                request_serializer=llm__pb2.ChatCompletionRequest.SerializeToString,
                response_deserializer=llm__pb2.ChatCompletionResponse.FromString,
                _registered_method=True)
        self.ChatCompletionStream = channel.unary_stream(
                '/llm.LLMProxyService/ChatCompletionStream',
                request_serializer=llm__pb2.ChatCompletionRequest.SerializeToString,
                response_deserializer=llm__pb2.ChatCompletionChunk.FromString,
                _registered_method=True)
        self.GetEmbedding = channel.unary_unary(
                '/llm.LLMProxyService/GetEmbedding',
                request_serializer=llm__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=llm__pb2.EmbeddingResponse.FromString,
                _registered_method=True)


class LLMProxyServiceServicer(object):
    """LLM 代理服务（适配 Azure OpenAI Chat Completions API）
    """

    def ChatCompletion(self, request, context):
        """非流式对话
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatCompletionStream(self, request, context):
        """流式对话（stream=true）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbedding(self, request, context):
        """获取 Embedding 向量（用于记忆向量化）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMProxyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatCompletion,
                    request_deserializer=llm__pb2.ChatCompletionRequest.FromString,
                    response_serializer=llm__pb2.ChatCompletionResponse.SerializeToString,
            ),
            'ChatCompletionStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatCompletionStream,
                    request_deserializer=llm__pb2.ChatCompletionRequest.FromString,
                    response_serializer=llm__pb2.ChatCompletionChunk.SerializeToString,
            ),
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=llm__pb2.EmbeddingRequest.FromString,
                    response_serializer=llm__pb2.EmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm.LLMProxyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm.LLMProxyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMProxyService(object):
    """LLM 代理服务（适配 Azure OpenAI Chat Completions API）
    """

    @staticmethod
    def ChatCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMProxyService/ChatCompletion',
            llm__pb2.ChatCompletionRequest.SerializeToString,
            llm__pb2.ChatCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatCompletionStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/llm.LLMProxyService/ChatCompletionStream',
            llm__pb2.ChatCompletionRequest.SerializeToString,
            llm__pb2.ChatCompletionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMProxyService/GetEmbedding',
            llm__pb2.EmbeddingRequest.SerializeToString,
            llm__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
