# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import storage_pb2 as storage__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageServiceStub(object):
    """============================================================================
    存储服务定义
    Go 端只负责存储操作，不关心业务语义（中期/长期记忆的区分由业务端控制）
    ============================================================================

    ======================== MySQL 统一操作 ========================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/storage.StorageService/Execute',
                request_serializer=storage__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=storage__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.ExecuteVector = channel.unary_unary(
                '/storage.StorageService/ExecuteVector',
                request_serializer=storage__pb2.ExecuteVectorRequest.SerializeToString,
                response_deserializer=storage__pb2.ExecuteVectorResponse.FromString,
                _registered_method=True)


class StorageServiceServicer(object):
    """============================================================================
    存储服务定义
    Go 端只负责存储操作，不关心业务语义（中期/长期记忆的区分由业务端控制）
    ============================================================================

    ======================== MySQL 统一操作 ========================
    """

    def Execute(self, request, context):
        """批量执行（按顺序执行多个 CRUD 操作，可选事务）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteVector(self, request, context):
        """======================== Milvus 统一操作 ========================

        批量执行向量操作（按顺序执行多个 Insert/Search/Delete 操作）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=storage__pb2.ExecuteRequest.FromString,
                    response_serializer=storage__pb2.ExecuteResponse.SerializeToString,
            ),
            'ExecuteVector': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteVector,
                    request_deserializer=storage__pb2.ExecuteVectorRequest.FromString,
                    response_serializer=storage__pb2.ExecuteVectorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storage.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('storage.StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """============================================================================
    存储服务定义
    Go 端只负责存储操作，不关心业务语义（中期/长期记忆的区分由业务端控制）
    ============================================================================

    ======================== MySQL 统一操作 ========================
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/Execute',
            storage__pb2.ExecuteRequest.SerializeToString,
            storage__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/ExecuteVector',
            storage__pb2.ExecuteVectorRequest.SerializeToString,
            storage__pb2.ExecuteVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
