// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: llm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息内容类型（支持多模态）
type ContentPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                         // "text" / "image_url"
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                         // type="text" 时使用
	ImageUrl      *ImageUrl              `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"` // type="image_url" 时使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentPart) Reset() {
	*x = ContentPart{}
	mi := &file_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentPart) ProtoMessage() {}

func (x *ContentPart) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentPart.ProtoReflect.Descriptor instead.
func (*ContentPart) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{0}
}

func (x *ContentPart) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContentPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ContentPart) GetImageUrl() *ImageUrl {
	if x != nil {
		return x.ImageUrl
	}
	return nil
}

type ImageUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`       // 图片 URL 或 base64
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"` // "low" / "high" / "auto"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageUrl) Reset() {
	*x = ImageUrl{}
	mi := &file_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUrl) ProtoMessage() {}

func (x *ImageUrl) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUrl.ProtoReflect.Descriptor instead.
func (*ImageUrl) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{1}
}

func (x *ImageUrl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageUrl) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ContentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*ContentPart         `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentList) Reset() {
	*x = ContentList{}
	mi := &file_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentList) ProtoMessage() {}

func (x *ContentList) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentList.ProtoReflect.Descriptor instead.
func (*ContentList) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{2}
}

func (x *ContentList) GetParts() []*ContentPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

// 单条消息（适配 Azure OpenAI 格式）
type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Role  string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "system" / "user" / "assistant" / "tool"
	// Types that are valid to be assigned to ContentType:
	//
	//	*ChatMessage_Content
	//	*ChatMessage_ContentParts
	ContentType   isChatMessage_ContentType `protobuf_oneof:"content_type"`
	Name          string                    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                 // 可选，发送者名称
	ToolCalls     []*ToolCall               `protobuf:"bytes,5,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`      // assistant 的工具调用请求
	ToolCallId    string                    `protobuf:"bytes,6,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"` // role="tool" 时，对应的 tool_call id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContentType() isChatMessage_ContentType {
	if x != nil {
		return x.ContentType
	}
	return nil
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		if x, ok := x.ContentType.(*ChatMessage_Content); ok {
			return x.Content
		}
	}
	return ""
}

func (x *ChatMessage) GetContentParts() *ContentList {
	if x != nil {
		if x, ok := x.ContentType.(*ChatMessage_ContentParts); ok {
			return x.ContentParts
		}
	}
	return nil
}

func (x *ChatMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatMessage) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatMessage) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

type isChatMessage_ContentType interface {
	isChatMessage_ContentType()
}

type ChatMessage_Content struct {
	Content string `protobuf:"bytes,2,opt,name=content,proto3,oneof"` // 简单文本内容
}

type ChatMessage_ContentParts struct {
	ContentParts *ContentList `protobuf:"bytes,3,opt,name=content_parts,json=contentParts,proto3,oneof"` // 多模态内容（图片+文本）
}

func (*ChatMessage_Content) isChatMessage_ContentType() {}

func (*ChatMessage_ContentParts) isChatMessage_ContentType() {}

type ChatCompletionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 必填参数
	DeploymentId string         `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"` // 模型部署 ID：gpt-5 / gpt-5-mini / gpt-5-nano / gpt-5-chat
	ApiVersion   string         `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`       // API 版本：2024-05-01-preview
	Messages     []*ChatMessage `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`                             // 对话历史
	// 可选参数
	Temperature      float32  `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`                                   // 温度参数 (0-2)，默认 1
	MaxTokens        int32    `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`                       // 最大生成 token 数
	TopP             float32  `protobuf:"fixed32,6,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`                                     // nucleus sampling，默认 1
	FrequencyPenalty float32  `protobuf:"fixed32,7,opt,name=frequency_penalty,json=frequencyPenalty,proto3" json:"frequency_penalty,omitempty"` // 频率惩罚 (-2 到 2)，默认 0
	PresencePenalty  float32  `protobuf:"fixed32,8,opt,name=presence_penalty,json=presencePenalty,proto3" json:"presence_penalty,omitempty"`    // 存在惩罚 (-2 到 2)，默认 0
	Stop             []string `protobuf:"bytes,9,rep,name=stop,proto3" json:"stop,omitempty"`                                                   // 停止词列表
	User             string   `protobuf:"bytes,10,opt,name=user,proto3" json:"user,omitempty"`                                                  // 用户标识（用于滥用检测）
	// 高级参数
	N              int32  `protobuf:"varint,11,opt,name=n,proto3" json:"n,omitempty"`                                                // 返回几个候选回复，默认 1
	Seed           int32  `protobuf:"varint,12,opt,name=seed,proto3" json:"seed,omitempty"`                                          // 随机种子（用于可复现结果）
	ResponseFormat string `protobuf:"bytes,13,opt,name=response_format,json=responseFormat,proto3" json:"response_format,omitempty"` // "text" / "json_object"
	// Function Calling / Tools
	Tools         []*Tool `protobuf:"bytes,14,rep,name=tools,proto3" json:"tools,omitempty"`                             // 可用工具列表
	ToolChoice    string  `protobuf:"bytes,15,opt,name=tool_choice,json=toolChoice,proto3" json:"tool_choice,omitempty"` // "none" / "auto" / "required" 或指定工具名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionRequest) Reset() {
	*x = ChatCompletionRequest{}
	mi := &file_llm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionRequest) ProtoMessage() {}

func (x *ChatCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionRequest.ProtoReflect.Descriptor instead.
func (*ChatCompletionRequest) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{4}
}

func (x *ChatCompletionRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *ChatCompletionRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ChatCompletionRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatCompletionRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ChatCompletionRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ChatCompletionRequest) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *ChatCompletionRequest) GetFrequencyPenalty() float32 {
	if x != nil {
		return x.FrequencyPenalty
	}
	return 0
}

func (x *ChatCompletionRequest) GetPresencePenalty() float32 {
	if x != nil {
		return x.PresencePenalty
	}
	return 0
}

func (x *ChatCompletionRequest) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *ChatCompletionRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ChatCompletionRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *ChatCompletionRequest) GetSeed() int32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *ChatCompletionRequest) GetResponseFormat() string {
	if x != nil {
		return x.ResponseFormat
	}
	return ""
}

func (x *ChatCompletionRequest) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ChatCompletionRequest) GetToolChoice() string {
	if x != nil {
		return x.ToolChoice
	}
	return ""
}

type ChatCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`            // 请求 ID
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`    // "chat.completion"
	Created       int64                  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"` // 创建时间戳
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`      // 实际使用的模型
	Choices       []*Choice              `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`  // 回复选项
	Usage         *Usage                 `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`      // token 使用统计
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionResponse) Reset() {
	*x = ChatCompletionResponse{}
	mi := &file_llm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionResponse) ProtoMessage() {}

func (x *ChatCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionResponse.ProtoReflect.Descriptor instead.
func (*ChatCompletionResponse) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{5}
}

func (x *ChatCompletionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ChatCompletionResponse) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionResponse) GetChoices() []*Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletionResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Choice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                                  // 选项索引
	Message       *ChatMessage           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                               // 回复消息
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"` // "stop" / "length" / "content_filter" / "tool_calls"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_llm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{6}
}

func (x *Choice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Choice) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Choice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type ChatCompletionChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`            // 请求 ID
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`    // "chat.completion.chunk"
	Created       int64                  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"` // 创建时间戳
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`      // 实际使用的模型
	Choices       []*StreamChoice        `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`  // 流式选项
	Usage         *Usage                 `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`      // token 统计（仅最后一个 chunk 有值）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionChunk) Reset() {
	*x = ChatCompletionChunk{}
	mi := &file_llm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChunk) ProtoMessage() {}

func (x *ChatCompletionChunk) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChunk.ProtoReflect.Descriptor instead.
func (*ChatCompletionChunk) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{7}
}

func (x *ChatCompletionChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionChunk) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ChatCompletionChunk) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletionChunk) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionChunk) GetChoices() []*StreamChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletionChunk) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type StreamChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                                  // 选项索引
	Delta         *ChatMessageDelta      `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`                                   // 增量内容
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"` // 结束原因（仅最后一个 chunk 有值）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChoice) Reset() {
	*x = StreamChoice{}
	mi := &file_llm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChoice) ProtoMessage() {}

func (x *StreamChoice) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChoice.ProtoReflect.Descriptor instead.
func (*StreamChoice) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{8}
}

func (x *StreamChoice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *StreamChoice) GetDelta() *ChatMessageDelta {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *StreamChoice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type ChatMessageDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`       // 角色（仅第一个 chunk 有值）
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 增量文本内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageDelta) Reset() {
	*x = ChatMessageDelta{}
	mi := &file_llm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageDelta) ProtoMessage() {}

func (x *ChatMessageDelta) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageDelta.ProtoReflect.Descriptor instead.
func (*ChatMessageDelta) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{9}
}

func (x *ChatMessageDelta) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessageDelta) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`             // 输入 token 数
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"` // 输出 token 数
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`                // 总 token 数
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_llm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{10}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

// 工具定义
type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`         // 目前只支持 "function"
	Function      *FunctionDefinition    `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"` // 函数定义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_llm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{11}
}

func (x *Tool) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Tool) GetFunction() *FunctionDefinition {
	if x != nil {
		return x.Function
	}
	return nil
}

type FunctionDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // 函数名称
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // 函数描述
	Parameters    string                 `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`   // JSON Schema 格式的参数定义（JSON 字符串）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionDefinition) Reset() {
	*x = FunctionDefinition{}
	mi := &file_llm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDefinition) ProtoMessage() {}

func (x *FunctionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDefinition.ProtoReflect.Descriptor instead.
func (*FunctionDefinition) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{12}
}

func (x *FunctionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionDefinition) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

// 工具调用（LLM 返回）
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // 调用 ID
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`         // "function"
	Function      *FunctionCall          `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"` // 函数调用详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_llm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{13}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolCall) GetFunction() *FunctionCall {
	if x != nil {
		return x.Function
	}
	return nil
}

type FunctionCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`           // 函数名称
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"` // 函数参数（JSON 字符串）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCall) Reset() {
	*x = FunctionCall{}
	mi := &file_llm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCall) ProtoMessage() {}

func (x *FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCall.ProtoReflect.Descriptor instead.
func (*FunctionCall) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{14}
}

func (x *FunctionCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type EmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"` // Embedding 模型部署 ID
	ApiVersion    string                 `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`       // API 版本
	Input         []string               `protobuf:"bytes,3,rep,name=input,proto3" json:"input,omitempty"`                                   // 待向量化文本列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingRequest) Reset() {
	*x = EmbeddingRequest{}
	mi := &file_llm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRequest) ProtoMessage() {}

func (x *EmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{15}
}

func (x *EmbeddingRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *EmbeddingRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *EmbeddingRequest) GetInput() []string {
	if x != nil {
		return x.Input
	}
	return nil
}

type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        string                 `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"` // "list"
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`   // 实际使用的模型
	Data          []*EmbeddingData       `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`     // Embedding 数据列表
	Usage         *Usage                 `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`   // token 使用统计
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_llm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{16}
}

func (x *EmbeddingResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *EmbeddingResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbeddingResponse) GetData() []*EmbeddingData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EmbeddingResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type EmbeddingData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                 // 索引
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`                // "embedding"
	Embedding     []float32              `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"` // 向量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingData) Reset() {
	*x = EmbeddingData{}
	mi := &file_llm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingData) ProtoMessage() {}

func (x *EmbeddingData) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingData.ProtoReflect.Descriptor instead.
func (*EmbeddingData) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{17}
}

func (x *EmbeddingData) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EmbeddingData) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *EmbeddingData) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

var File_llm_proto protoreflect.FileDescriptor

const file_llm_proto_rawDesc = "" +
	"\n" +
	"\tllm.proto\x12\x03llm\"a\n" +
	"\vContentPart\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12*\n" +
	"\timage_url\x18\x03 \x01(\v2\r.llm.ImageUrlR\bimageUrl\"4\n" +
	"\bImageUrl\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"5\n" +
	"\vContentList\x12&\n" +
	"\x05parts\x18\x01 \x03(\v2\x10.llm.ContentPartR\x05parts\"\xea\x01\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1a\n" +
	"\acontent\x18\x02 \x01(\tH\x00R\acontent\x127\n" +
	"\rcontent_parts\x18\x03 \x01(\v2\x10.llm.ContentListH\x00R\fcontentParts\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12,\n" +
	"\n" +
	"tool_calls\x18\x05 \x03(\v2\r.llm.ToolCallR\ttoolCalls\x12 \n" +
	"\ftool_call_id\x18\x06 \x01(\tR\n" +
	"toolCallIdB\x0e\n" +
	"\fcontent_type\"\xee\x03\n" +
	"\x15ChatCompletionRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12,\n" +
	"\bmessages\x18\x03 \x03(\v2\x10.llm.ChatMessageR\bmessages\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12\x13\n" +
	"\x05top_p\x18\x06 \x01(\x02R\x04topP\x12+\n" +
	"\x11frequency_penalty\x18\a \x01(\x02R\x10frequencyPenalty\x12)\n" +
	"\x10presence_penalty\x18\b \x01(\x02R\x0fpresencePenalty\x12\x12\n" +
	"\x04stop\x18\t \x03(\tR\x04stop\x12\x12\n" +
	"\x04user\x18\n" +
	" \x01(\tR\x04user\x12\f\n" +
	"\x01n\x18\v \x01(\x05R\x01n\x12\x12\n" +
	"\x04seed\x18\f \x01(\x05R\x04seed\x12'\n" +
	"\x0fresponse_format\x18\r \x01(\tR\x0eresponseFormat\x12\x1f\n" +
	"\x05tools\x18\x0e \x03(\v2\t.llm.ToolR\x05tools\x12\x1f\n" +
	"\vtool_choice\x18\x0f \x01(\tR\n" +
	"toolChoice\"\xb9\x01\n" +
	"\x16ChatCompletionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12%\n" +
	"\achoices\x18\x05 \x03(\v2\v.llm.ChoiceR\achoices\x12 \n" +
	"\x05usage\x18\x06 \x01(\v2\n" +
	".llm.UsageR\x05usage\"o\n" +
	"\x06Choice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12*\n" +
	"\amessage\x18\x02 \x01(\v2\x10.llm.ChatMessageR\amessage\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"\xbc\x01\n" +
	"\x13ChatCompletionChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12+\n" +
	"\achoices\x18\x05 \x03(\v2\x11.llm.StreamChoiceR\achoices\x12 \n" +
	"\x05usage\x18\x06 \x01(\v2\n" +
	".llm.UsageR\x05usage\"v\n" +
	"\fStreamChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12+\n" +
	"\x05delta\x18\x02 \x01(\v2\x15.llm.ChatMessageDeltaR\x05delta\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"@\n" +
	"\x10ChatMessageDelta\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"O\n" +
	"\x04Tool\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x123\n" +
	"\bfunction\x18\x02 \x01(\v2\x17.llm.FunctionDefinitionR\bfunction\"j\n" +
	"\x12FunctionDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\tR\n" +
	"parameters\"]\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12-\n" +
	"\bfunction\x18\x03 \x01(\v2\x11.llm.FunctionCallR\bfunction\"@\n" +
	"\fFunctionCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\"n\n" +
	"\x10EmbeddingRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12\x14\n" +
	"\x05input\x18\x03 \x03(\tR\x05input\"\x8b\x01\n" +
	"\x11EmbeddingResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.llm.EmbeddingDataR\x04data\x12 \n" +
	"\x05usage\x18\x04 \x01(\v2\n" +
	".llm.UsageR\x05usage\"[\n" +
	"\rEmbeddingData\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x02R\tembedding2\xeb\x01\n" +
	"\x0fLLMProxyService\x12I\n" +
	"\x0eChatCompletion\x12\x1a.llm.ChatCompletionRequest\x1a\x1b.llm.ChatCompletionResponse\x12N\n" +
	"\x14ChatCompletionStream\x12\x1a.llm.ChatCompletionRequest\x1a\x18.llm.ChatCompletionChunk0\x01\x12=\n" +
	"\fGetEmbedding\x12\x15.llm.EmbeddingRequest\x1a\x16.llm.EmbeddingResponseB\x1fZ\x1dbot_agent/storage/internal/pbb\x06proto3"

var (
	file_llm_proto_rawDescOnce sync.Once
	file_llm_proto_rawDescData []byte
)

func file_llm_proto_rawDescGZIP() []byte {
	file_llm_proto_rawDescOnce.Do(func() {
		file_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_proto_rawDesc), len(file_llm_proto_rawDesc)))
	})
	return file_llm_proto_rawDescData
}

var file_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_llm_proto_goTypes = []any{
	(*ContentPart)(nil),            // 0: llm.ContentPart
	(*ImageUrl)(nil),               // 1: llm.ImageUrl
	(*ContentList)(nil),            // 2: llm.ContentList
	(*ChatMessage)(nil),            // 3: llm.ChatMessage
	(*ChatCompletionRequest)(nil),  // 4: llm.ChatCompletionRequest
	(*ChatCompletionResponse)(nil), // 5: llm.ChatCompletionResponse
	(*Choice)(nil),                 // 6: llm.Choice
	(*ChatCompletionChunk)(nil),    // 7: llm.ChatCompletionChunk
	(*StreamChoice)(nil),           // 8: llm.StreamChoice
	(*ChatMessageDelta)(nil),       // 9: llm.ChatMessageDelta
	(*Usage)(nil),                  // 10: llm.Usage
	(*Tool)(nil),                   // 11: llm.Tool
	(*FunctionDefinition)(nil),     // 12: llm.FunctionDefinition
	(*ToolCall)(nil),               // 13: llm.ToolCall
	(*FunctionCall)(nil),           // 14: llm.FunctionCall
	(*EmbeddingRequest)(nil),       // 15: llm.EmbeddingRequest
	(*EmbeddingResponse)(nil),      // 16: llm.EmbeddingResponse
	(*EmbeddingData)(nil),          // 17: llm.EmbeddingData
}
var file_llm_proto_depIdxs = []int32{
	1,  // 0: llm.ContentPart.image_url:type_name -> llm.ImageUrl
	0,  // 1: llm.ContentList.parts:type_name -> llm.ContentPart
	2,  // 2: llm.ChatMessage.content_parts:type_name -> llm.ContentList
	13, // 3: llm.ChatMessage.tool_calls:type_name -> llm.ToolCall
	3,  // 4: llm.ChatCompletionRequest.messages:type_name -> llm.ChatMessage
	11, // 5: llm.ChatCompletionRequest.tools:type_name -> llm.Tool
	6,  // 6: llm.ChatCompletionResponse.choices:type_name -> llm.Choice
	10, // 7: llm.ChatCompletionResponse.usage:type_name -> llm.Usage
	3,  // 8: llm.Choice.message:type_name -> llm.ChatMessage
	8,  // 9: llm.ChatCompletionChunk.choices:type_name -> llm.StreamChoice
	10, // 10: llm.ChatCompletionChunk.usage:type_name -> llm.Usage
	9,  // 11: llm.StreamChoice.delta:type_name -> llm.ChatMessageDelta
	12, // 12: llm.Tool.function:type_name -> llm.FunctionDefinition
	14, // 13: llm.ToolCall.function:type_name -> llm.FunctionCall
	17, // 14: llm.EmbeddingResponse.data:type_name -> llm.EmbeddingData
	10, // 15: llm.EmbeddingResponse.usage:type_name -> llm.Usage
	4,  // 16: llm.LLMProxyService.ChatCompletion:input_type -> llm.ChatCompletionRequest
	4,  // 17: llm.LLMProxyService.ChatCompletionStream:input_type -> llm.ChatCompletionRequest
	15, // 18: llm.LLMProxyService.GetEmbedding:input_type -> llm.EmbeddingRequest
	5,  // 19: llm.LLMProxyService.ChatCompletion:output_type -> llm.ChatCompletionResponse
	7,  // 20: llm.LLMProxyService.ChatCompletionStream:output_type -> llm.ChatCompletionChunk
	16, // 21: llm.LLMProxyService.GetEmbedding:output_type -> llm.EmbeddingResponse
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_llm_proto_init() }
func file_llm_proto_init() {
	if File_llm_proto != nil {
		return
	}
	file_llm_proto_msgTypes[3].OneofWrappers = []any{
		(*ChatMessage_Content)(nil),
		(*ChatMessage_ContentParts)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_proto_rawDesc), len(file_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_proto_goTypes,
		DependencyIndexes: file_llm_proto_depIdxs,
		MessageInfos:      file_llm_proto_msgTypes,
	}.Build()
	File_llm_proto = out.File
	file_llm_proto_goTypes = nil
	file_llm_proto_depIdxs = nil
}
