// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: llm.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMProxyService_ChatCompletion_FullMethodName       = "/llm.LLMProxyService/ChatCompletion"
	LLMProxyService_ChatCompletionStream_FullMethodName = "/llm.LLMProxyService/ChatCompletionStream"
	LLMProxyService_GetEmbedding_FullMethodName         = "/llm.LLMProxyService/GetEmbedding"
)

// LLMProxyServiceClient is the client API for LLMProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LLM 代理服务（适配 Azure OpenAI Chat Completions API）
type LLMProxyServiceClient interface {
	// 非流式对话
	ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error)
	// 流式对话（stream=true）
	ChatCompletionStream(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionChunk], error)
	// 获取 Embedding 向量（用于记忆向量化）
	GetEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
}

type lLMProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMProxyServiceClient(cc grpc.ClientConnInterface) LLMProxyServiceClient {
	return &lLMProxyServiceClient{cc}
}

func (c *lLMProxyServiceClient) ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatCompletionResponse)
	err := c.cc.Invoke(ctx, LLMProxyService_ChatCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMProxyServiceClient) ChatCompletionStream(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LLMProxyService_ServiceDesc.Streams[0], LLMProxyService_ChatCompletionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatCompletionRequest, ChatCompletionChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMProxyService_ChatCompletionStreamClient = grpc.ServerStreamingClient[ChatCompletionChunk]

func (c *lLMProxyServiceClient) GetEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, LLMProxyService_GetEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMProxyServiceServer is the server API for LLMProxyService service.
// All implementations must embed UnimplementedLLMProxyServiceServer
// for forward compatibility.
//
// LLM 代理服务（适配 Azure OpenAI Chat Completions API）
type LLMProxyServiceServer interface {
	// 非流式对话
	ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error)
	// 流式对话（stream=true）
	ChatCompletionStream(*ChatCompletionRequest, grpc.ServerStreamingServer[ChatCompletionChunk]) error
	// 获取 Embedding 向量（用于记忆向量化）
	GetEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error)
	mustEmbedUnimplementedLLMProxyServiceServer()
}

// UnimplementedLLMProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMProxyServiceServer struct{}

func (UnimplementedLLMProxyServiceServer) ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatCompletion not implemented")
}
func (UnimplementedLLMProxyServiceServer) ChatCompletionStream(*ChatCompletionRequest, grpc.ServerStreamingServer[ChatCompletionChunk]) error {
	return status.Error(codes.Unimplemented, "method ChatCompletionStream not implemented")
}
func (UnimplementedLLMProxyServiceServer) GetEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmbedding not implemented")
}
func (UnimplementedLLMProxyServiceServer) mustEmbedUnimplementedLLMProxyServiceServer() {}
func (UnimplementedLLMProxyServiceServer) testEmbeddedByValue()                         {}

// UnsafeLLMProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMProxyServiceServer will
// result in compilation errors.
type UnsafeLLMProxyServiceServer interface {
	mustEmbedUnimplementedLLMProxyServiceServer()
}

func RegisterLLMProxyServiceServer(s grpc.ServiceRegistrar, srv LLMProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedLLMProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMProxyService_ServiceDesc, srv)
}

func _LLMProxyService_ChatCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMProxyServiceServer).ChatCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMProxyService_ChatCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMProxyServiceServer).ChatCompletion(ctx, req.(*ChatCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMProxyService_ChatCompletionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatCompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LLMProxyServiceServer).ChatCompletionStream(m, &grpc.GenericServerStream[ChatCompletionRequest, ChatCompletionChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMProxyService_ChatCompletionStreamServer = grpc.ServerStreamingServer[ChatCompletionChunk]

func _LLMProxyService_GetEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMProxyServiceServer).GetEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMProxyService_GetEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMProxyServiceServer).GetEmbedding(ctx, req.(*EmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMProxyService_ServiceDesc is the grpc.ServiceDesc for LLMProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm.LLMProxyService",
	HandlerType: (*LLMProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChatCompletion",
			Handler:    _LLMProxyService_ChatCompletion_Handler,
		},
		{
			MethodName: "GetEmbedding",
			Handler:    _LLMProxyService_GetEmbedding_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatCompletionStream",
			Handler:       _LLMProxyService_ChatCompletionStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "llm.proto",
}
