// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: storage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NULL 值枚举
type NullValue int32

const (
	NullValue_NULL_VALUE NullValue = 0
)

// Enum value maps for NullValue.
var (
	NullValue_name = map[int32]string{
		0: "NULL_VALUE",
	}
	NullValue_value = map[string]int32{
		"NULL_VALUE": 0,
	}
)

func (x NullValue) Enum() *NullValue {
	p := new(NullValue)
	*p = x
	return p
}

func (x NullValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NullValue) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_proto_enumTypes[0].Descriptor()
}

func (NullValue) Type() protoreflect.EnumType {
	return &file_storage_proto_enumTypes[0]
}

func (x NullValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NullValue.Descriptor instead.
func (NullValue) EnumDescriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

// 带类型的值，支持多种数据类型
type TypedValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*TypedValue_StringValue
	//	*TypedValue_IntValue
	//	*TypedValue_DoubleValue
	//	*TypedValue_BoolValue
	//	*TypedValue_BytesValue
	//	*TypedValue_TimestampValue
	//	*TypedValue_NullValue
	Value         isTypedValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedValue) Reset() {
	*x = TypedValue{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedValue) ProtoMessage() {}

func (x *TypedValue) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedValue.ProtoReflect.Descriptor instead.
func (*TypedValue) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *TypedValue) GetValue() isTypedValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TypedValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *TypedValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *TypedValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *TypedValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *TypedValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *TypedValue) GetTimestampValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return 0
}

func (x *TypedValue) GetNullValue() NullValue {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_NullValue); ok {
			return x.NullValue
		}
	}
	return NullValue_NULL_VALUE
}

type isTypedValue_Value interface {
	isTypedValue_Value()
}

type TypedValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"` // 字符串
}

type TypedValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"` // 整数（包含 int32, int64）
}

type TypedValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"` // 浮点数（包含 float, double）
}

type TypedValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"` // 布尔值
}

type TypedValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"` // 二进制数据
}

type TypedValue_TimestampValue struct {
	TimestampValue int64 `protobuf:"varint,6,opt,name=timestamp_value,json=timestampValue,proto3,oneof"` // 时间戳（Unix 毫秒）
}

type TypedValue_NullValue struct {
	NullValue NullValue `protobuf:"varint,7,opt,name=null_value,json=nullValue,proto3,enum=storage.NullValue,oneof"` // NULL 值
}

func (*TypedValue_StringValue) isTypedValue_Value() {}

func (*TypedValue_IntValue) isTypedValue_Value() {}

func (*TypedValue_DoubleValue) isTypedValue_Value() {}

func (*TypedValue_BoolValue) isTypedValue_Value() {}

func (*TypedValue_BytesValue) isTypedValue_Value() {}

func (*TypedValue_TimestampValue) isTypedValue_Value() {}

func (*TypedValue_NullValue) isTypedValue_Value() {}

// 批量执行请求
type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Operations     []*Operation           `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`                                // 操作列表，按顺序执行
	UseTransaction bool                   `protobuf:"varint,2,opt,name=use_transaction,json=useTransaction,proto3" json:"use_transaction,omitempty"` // 是否使用事务（失败自动回滚）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteRequest) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ExecuteRequest) GetUseTransaction() bool {
	if x != nil {
		return x.UseTransaction
	}
	return false
}

// 单个操作 - 使用 oneof 拆分不同操作类型，解决结构臃肿问题
type Operation struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Database string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"` // 数据库名
	Table    string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`       // 表名
	// Types that are valid to be assigned to Operation:
	//
	//	*Operation_Insert
	//	*Operation_Update
	//	*Operation_Delete
	//	*Operation_Select
	Operation     isOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *Operation) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Operation) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *Operation) GetOperation() isOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *Operation) GetInsert() *InsertOperation {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Insert); ok {
			return x.Insert
		}
	}
	return nil
}

func (x *Operation) GetUpdate() *UpdateOperation {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *Operation) GetDelete() *DeleteOperation {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Operation) GetSelect() *SelectOperation {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Select); ok {
			return x.Select
		}
	}
	return nil
}

type isOperation_Operation interface {
	isOperation_Operation()
}

type Operation_Insert struct {
	Insert *InsertOperation `protobuf:"bytes,3,opt,name=insert,proto3,oneof"` // 插入操作
}

type Operation_Update struct {
	Update *UpdateOperation `protobuf:"bytes,4,opt,name=update,proto3,oneof"` // 更新操作
}

type Operation_Delete struct {
	Delete *DeleteOperation `protobuf:"bytes,5,opt,name=delete,proto3,oneof"` // 删除操作
}

type Operation_Select struct {
	Select *SelectOperation `protobuf:"bytes,6,opt,name=select,proto3,oneof"` // 查询操作
}

func (*Operation_Insert) isOperation_Operation() {}

func (*Operation_Update) isOperation_Operation() {}

func (*Operation_Delete) isOperation_Operation() {}

func (*Operation_Select) isOperation_Operation() {}

// ======================== INSERT 操作 ========================
type InsertOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*InsertRow           `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"` // 插入行数据(支持批量插入)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertOperation) Reset() {
	*x = InsertOperation{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertOperation) ProtoMessage() {}

func (x *InsertOperation) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertOperation.ProtoReflect.Descriptor instead.
func (*InsertOperation) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *InsertOperation) GetRows() []*InsertRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

// 插入行数据
type InsertRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*TypedValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 字段名 -> 带类型的值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRow) Reset() {
	*x = InsertRow{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRow) ProtoMessage() {}

func (x *InsertRow) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRow.ProtoReflect.Descriptor instead.
func (*InsertRow) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *InsertRow) GetFields() map[string]*TypedValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

// ======================== UPDATE 操作 ========================
type UpdateOperation struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SetFields map[string]*TypedValue `protobuf:"bytes,1,rep,name=set_fields,json=setFields,proto3" json:"set_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 要更新的字段（简单赋值）
	Where     *WhereClause           `protobuf:"bytes,2,opt,name=where,proto3" json:"where,omitempty"`                                                                                                    // WHERE 条件
	// 原始 SET 子句，支持 SQL 表达式（如 "access_count = access_count + 1, updated_at = NOW()"）
	// 当 raw_set 不为空时，优先使用 raw_set，忽略 set_fields
	RawSet        string        `protobuf:"bytes,3,opt,name=raw_set,json=rawSet,proto3" json:"raw_set,omitempty"`
	RawSetParams  []*TypedValue `protobuf:"bytes,4,rep,name=raw_set_params,json=rawSetParams,proto3" json:"raw_set_params,omitempty"` // raw_set 中占位符(?)对应的参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOperation) Reset() {
	*x = UpdateOperation{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOperation) ProtoMessage() {}

func (x *UpdateOperation) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOperation.ProtoReflect.Descriptor instead.
func (*UpdateOperation) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOperation) GetSetFields() map[string]*TypedValue {
	if x != nil {
		return x.SetFields
	}
	return nil
}

func (x *UpdateOperation) GetWhere() *WhereClause {
	if x != nil {
		return x.Where
	}
	return nil
}

func (x *UpdateOperation) GetRawSet() string {
	if x != nil {
		return x.RawSet
	}
	return ""
}

func (x *UpdateOperation) GetRawSetParams() []*TypedValue {
	if x != nil {
		return x.RawSetParams
	}
	return nil
}

// ======================== DELETE 操作 ========================
type DeleteOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Where         *WhereClause           `protobuf:"bytes,1,opt,name=where,proto3" json:"where,omitempty"` // WHERE 条件（防止误删全表）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOperation) Reset() {
	*x = DeleteOperation{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOperation) ProtoMessage() {}

func (x *DeleteOperation) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOperation.ProtoReflect.Descriptor instead.
func (*DeleteOperation) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteOperation) GetWhere() *WhereClause {
	if x != nil {
		return x.Where
	}
	return nil
}

// ======================== SELECT 操作 ========================
type SelectOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`                  // 要返回的字段（空则返回全部）
	Where         *WhereClause           `protobuf:"bytes,2,opt,name=where,proto3" json:"where,omitempty"`                    // WHERE 条件
	OrderBy       *OrderBy               `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"` // 排序
	Pagination    *Pagination            `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`          // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectOperation) Reset() {
	*x = SelectOperation{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectOperation) ProtoMessage() {}

func (x *SelectOperation) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectOperation.ProtoReflect.Descriptor instead.
func (*SelectOperation) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *SelectOperation) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SelectOperation) GetWhere() *WhereClause {
	if x != nil {
		return x.Where
	}
	return nil
}

func (x *SelectOperation) GetOrderBy() *OrderBy {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *SelectOperation) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// WHERE 条件
type WhereClause struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 简单等值条件（AND 关系）
	Conditions map[string]*TypedValue `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 复杂 WHERE 子句（当简单条件无法满足时使用）
	RawClause string `protobuf:"bytes,2,opt,name=raw_clause,json=rawClause,proto3" json:"raw_clause,omitempty"`
	// 复杂条件的参数（防止 SQL 注入）
	RawParams     []*TypedValue `protobuf:"bytes,3,rep,name=raw_params,json=rawParams,proto3" json:"raw_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhereClause) Reset() {
	*x = WhereClause{}
	mi := &file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhereClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhereClause) ProtoMessage() {}

func (x *WhereClause) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhereClause.ProtoReflect.Descriptor instead.
func (*WhereClause) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

func (x *WhereClause) GetConditions() map[string]*TypedValue {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *WhereClause) GetRawClause() string {
	if x != nil {
		return x.RawClause
	}
	return ""
}

func (x *WhereClause) GetRawParams() []*TypedValue {
	if x != nil {
		return x.RawParams
	}
	return nil
}

// 排序
type OrderBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`            // 排序字段
	Descending    bool                   `protobuf:"varint,2,opt,name=descending,proto3" json:"descending,omitempty"` // 是否降序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBy) Reset() {
	*x = OrderBy{}
	mi := &file_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBy) ProtoMessage() {}

func (x *OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBy.ProtoReflect.Descriptor instead.
func (*OrderBy) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{9}
}

func (x *OrderBy) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *OrderBy) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

// 分页
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`   // 限制数量
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // 偏移量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{10}
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// 批量执行响应
type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*OperationResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`  // 每个操作的结果
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // 整体是否成功
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      // 错误信息（事务失败时返回）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteResponse) GetResults() []*OperationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 单个操作结果 - 使用 oneof 区分不同类型的结果
type OperationResult struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Index   int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 对应 operations 中的索引
	Success bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*OperationResult_InsertResult
	//	*OperationResult_UpdateResult
	//	*OperationResult_DeleteResult
	//	*OperationResult_SelectResult
	Result        isOperationResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResult) Reset() {
	*x = OperationResult{}
	mi := &file_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResult) ProtoMessage() {}

func (x *OperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResult.ProtoReflect.Descriptor instead.
func (*OperationResult) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{12}
}

func (x *OperationResult) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OperationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperationResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *OperationResult) GetResult() isOperationResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *OperationResult) GetInsertResult() *InsertResult {
	if x != nil {
		if x, ok := x.Result.(*OperationResult_InsertResult); ok {
			return x.InsertResult
		}
	}
	return nil
}

func (x *OperationResult) GetUpdateResult() *UpdateResult {
	if x != nil {
		if x, ok := x.Result.(*OperationResult_UpdateResult); ok {
			return x.UpdateResult
		}
	}
	return nil
}

func (x *OperationResult) GetDeleteResult() *DeleteResult {
	if x != nil {
		if x, ok := x.Result.(*OperationResult_DeleteResult); ok {
			return x.DeleteResult
		}
	}
	return nil
}

func (x *OperationResult) GetSelectResult() *SelectResult {
	if x != nil {
		if x, ok := x.Result.(*OperationResult_SelectResult); ok {
			return x.SelectResult
		}
	}
	return nil
}

type isOperationResult_Result interface {
	isOperationResult_Result()
}

type OperationResult_InsertResult struct {
	InsertResult *InsertResult `protobuf:"bytes,4,opt,name=insert_result,json=insertResult,proto3,oneof"` // 插入结果
}

type OperationResult_UpdateResult struct {
	UpdateResult *UpdateResult `protobuf:"bytes,5,opt,name=update_result,json=updateResult,proto3,oneof"` // 更新结果
}

type OperationResult_DeleteResult struct {
	DeleteResult *DeleteResult `protobuf:"bytes,6,opt,name=delete_result,json=deleteResult,proto3,oneof"` // 删除结果
}

type OperationResult_SelectResult struct {
	SelectResult *SelectResult `protobuf:"bytes,7,opt,name=select_result,json=selectResult,proto3,oneof"` // 查询结果
}

func (*OperationResult_InsertResult) isOperationResult_Result() {}

func (*OperationResult_UpdateResult) isOperationResult_Result() {}

func (*OperationResult_DeleteResult) isOperationResult_Result() {}

func (*OperationResult_SelectResult) isOperationResult_Result() {}

// 插入结果
type InsertResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InsertedCount int32                  `protobuf:"varint,1,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"` // 成功插入数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResult) Reset() {
	*x = InsertResult{}
	mi := &file_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResult) ProtoMessage() {}

func (x *InsertResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResult.ProtoReflect.Descriptor instead.
func (*InsertResult) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{13}
}

func (x *InsertResult) GetInsertedCount() int32 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

// 更新结果
type UpdateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffectedRows  int32                  `protobuf:"varint,1,opt,name=affected_rows,json=affectedRows,proto3" json:"affected_rows,omitempty"` // 影响行数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResult) Reset() {
	*x = UpdateResult{}
	mi := &file_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResult) ProtoMessage() {}

func (x *UpdateResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResult.ProtoReflect.Descriptor instead.
func (*UpdateResult) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateResult) GetAffectedRows() int32 {
	if x != nil {
		return x.AffectedRows
	}
	return 0
}

// 删除结果
type DeleteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffectedRows  int32                  `protobuf:"varint,1,opt,name=affected_rows,json=affectedRows,proto3" json:"affected_rows,omitempty"` // 影响行数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResult) Reset() {
	*x = DeleteResult{}
	mi := &file_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResult) ProtoMessage() {}

func (x *DeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResult.ProtoReflect.Descriptor instead.
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteResult) GetAffectedRows() int32 {
	if x != nil {
		return x.AffectedRows
	}
	return 0
}

// 查询结果
type SelectResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*ResultRow           `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`    // 查询结果行
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数（用于分页）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectResult) Reset() {
	*x = SelectResult{}
	mi := &file_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectResult) ProtoMessage() {}

func (x *SelectResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectResult.ProtoReflect.Descriptor instead.
func (*SelectResult) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{16}
}

func (x *SelectResult) GetRows() []*ResultRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *SelectResult) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 查询结果行（与 InsertRow 分离，语义清晰）
type ResultRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*TypedValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 字段名 -> 带类型的值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRow) Reset() {
	*x = ResultRow{}
	mi := &file_storage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRow) ProtoMessage() {}

func (x *ResultRow) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRow.ProtoReflect.Descriptor instead.
func (*ResultRow) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{17}
}

func (x *ResultRow) GetFields() map[string]*TypedValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 批量执行向量操作请求
type ExecuteVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*VectorOperation     `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"` // 向量操作列表，按顺序执行
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteVectorRequest) Reset() {
	*x = ExecuteVectorRequest{}
	mi := &file_storage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteVectorRequest) ProtoMessage() {}

func (x *ExecuteVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteVectorRequest.ProtoReflect.Descriptor instead.
func (*ExecuteVectorRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{18}
}

func (x *ExecuteVectorRequest) GetOperations() []*VectorOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

// 单个向量操作 - 使用 oneof 拆分
type VectorOperation struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Collection string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"` // Collection 名称
	Partition  string                 `protobuf:"bytes,2,opt,name=partition,proto3" json:"partition,omitempty"`   // Partition 名称（按 bot_id 分区，提升检索效率）
	// Types that are valid to be assigned to Operation:
	//
	//	*VectorOperation_Insert
	//	*VectorOperation_Search
	//	*VectorOperation_Delete
	//	*VectorOperation_Upsert
	Operation     isVectorOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorOperation) Reset() {
	*x = VectorOperation{}
	mi := &file_storage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorOperation) ProtoMessage() {}

func (x *VectorOperation) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorOperation.ProtoReflect.Descriptor instead.
func (*VectorOperation) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{19}
}

func (x *VectorOperation) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *VectorOperation) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *VectorOperation) GetOperation() isVectorOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *VectorOperation) GetInsert() *VectorInsertOperation {
	if x != nil {
		if x, ok := x.Operation.(*VectorOperation_Insert); ok {
			return x.Insert
		}
	}
	return nil
}

func (x *VectorOperation) GetSearch() *VectorSearchOperation {
	if x != nil {
		if x, ok := x.Operation.(*VectorOperation_Search); ok {
			return x.Search
		}
	}
	return nil
}

func (x *VectorOperation) GetDelete() *VectorDeleteOperation {
	if x != nil {
		if x, ok := x.Operation.(*VectorOperation_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *VectorOperation) GetUpsert() *VectorUpsertOperation {
	if x != nil {
		if x, ok := x.Operation.(*VectorOperation_Upsert); ok {
			return x.Upsert
		}
	}
	return nil
}

type isVectorOperation_Operation interface {
	isVectorOperation_Operation()
}

type VectorOperation_Insert struct {
	Insert *VectorInsertOperation `protobuf:"bytes,3,opt,name=insert,proto3,oneof"` // 插入操作
}

type VectorOperation_Search struct {
	Search *VectorSearchOperation `protobuf:"bytes,4,opt,name=search,proto3,oneof"` // 搜索操作
}

type VectorOperation_Delete struct {
	Delete *VectorDeleteOperation `protobuf:"bytes,5,opt,name=delete,proto3,oneof"` // 删除操作
}

type VectorOperation_Upsert struct {
	Upsert *VectorUpsertOperation `protobuf:"bytes,6,opt,name=upsert,proto3,oneof"` // 更新或插入操作
}

func (*VectorOperation_Insert) isVectorOperation_Operation() {}

func (*VectorOperation_Search) isVectorOperation_Operation() {}

func (*VectorOperation_Delete) isVectorOperation_Operation() {}

func (*VectorOperation_Upsert) isVectorOperation_Operation() {}

// ======================== 向量插入操作 ========================
type VectorInsertOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       []*VectorData          `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"` // 要插入的向量数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorInsertOperation) Reset() {
	*x = VectorInsertOperation{}
	mi := &file_storage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorInsertOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorInsertOperation) ProtoMessage() {}

func (x *VectorInsertOperation) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorInsertOperation.ProtoReflect.Descriptor instead.
func (*VectorInsertOperation) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{20}
}

func (x *VectorInsertOperation) GetVectors() []*VectorData {
	if x != nil {
		return x.Vectors
	}
	return nil
}

// ======================== 向量更新或插入操作 ========================
type VectorUpsertOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       []*VectorData          `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"` // 要更新或插入的向量数据（ID 存在则更新，否则插入）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorUpsertOperation) Reset() {
	*x = VectorUpsertOperation{}
	mi := &file_storage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorUpsertOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorUpsertOperation) ProtoMessage() {}

func (x *VectorUpsertOperation) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorUpsertOperation.ProtoReflect.Descriptor instead.
func (*VectorUpsertOperation) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{21}
}

func (x *VectorUpsertOperation) GetVectors() []*VectorData {
	if x != nil {
		return x.Vectors
	}
	return nil
}

// 向量数据
type VectorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // 向量 ID
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`                                                                      // 向量数据
	Metadata      map[string]*TypedValue `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 附加元数据（支持多种类型）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorData) Reset() {
	*x = VectorData{}
	mi := &file_storage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorData) ProtoMessage() {}

func (x *VectorData) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorData.ProtoReflect.Descriptor instead.
func (*VectorData) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{22}
}

func (x *VectorData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VectorData) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *VectorData) GetMetadata() map[string]*TypedValue {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ======================== 向量搜索操作 ========================
type VectorSearchOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryVector   []float32              `protobuf:"fixed32,1,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`                                     // 查询向量
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`                                                                  // 返回数量
	MinScore      float32                `protobuf:"fixed32,3,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`                                                     // 最小相似度阈值（可选，0 表示不限制）
	Filter        map[string]*TypedValue `protobuf:"bytes,4,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据过滤条件（可选，简单等值条件）
	FilterExpr    string                 `protobuf:"bytes,5,opt,name=filter_expr,json=filterExpr,proto3" json:"filter_expr,omitempty"`                                                 // 复杂过滤表达式（可选，Milvus 表达式语法）
	OutputFields  []string               `protobuf:"bytes,6,rep,name=output_fields,json=outputFields,proto3" json:"output_fields,omitempty"`                                           // 要返回的 metadata 字段（空则返回全部）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearchOperation) Reset() {
	*x = VectorSearchOperation{}
	mi := &file_storage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchOperation) ProtoMessage() {}

func (x *VectorSearchOperation) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchOperation.ProtoReflect.Descriptor instead.
func (*VectorSearchOperation) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{23}
}

func (x *VectorSearchOperation) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *VectorSearchOperation) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *VectorSearchOperation) GetMinScore() float32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *VectorSearchOperation) GetFilter() map[string]*TypedValue {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *VectorSearchOperation) GetFilterExpr() string {
	if x != nil {
		return x.FilterExpr
	}
	return ""
}

func (x *VectorSearchOperation) GetOutputFields() []string {
	if x != nil {
		return x.OutputFields
	}
	return nil
}

// ======================== 向量删除操作 ========================
type VectorDeleteOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`                                                                                 // 要删除的向量 ID 列表（按 ID 删除）
	Filter        map[string]*TypedValue `protobuf:"bytes,2,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据过滤条件（按条件删除，简单等值条件）
	FilterExpr    string                 `protobuf:"bytes,3,opt,name=filter_expr,json=filterExpr,proto3" json:"filter_expr,omitempty"`                                                 // 复杂过滤表达式（按条件删除，Milvus 表达式语法）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorDeleteOperation) Reset() {
	*x = VectorDeleteOperation{}
	mi := &file_storage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorDeleteOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorDeleteOperation) ProtoMessage() {}

func (x *VectorDeleteOperation) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorDeleteOperation.ProtoReflect.Descriptor instead.
func (*VectorDeleteOperation) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{24}
}

func (x *VectorDeleteOperation) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *VectorDeleteOperation) GetFilter() map[string]*TypedValue {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *VectorDeleteOperation) GetFilterExpr() string {
	if x != nil {
		return x.FilterExpr
	}
	return ""
}

// 批量执行向量操作响应
type ExecuteVectorResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Results       []*VectorOperationResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`  // 每个操作的结果
	Success       bool                     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // 整体是否成功
	Error         string                   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteVectorResponse) Reset() {
	*x = ExecuteVectorResponse{}
	mi := &file_storage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteVectorResponse) ProtoMessage() {}

func (x *ExecuteVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteVectorResponse.ProtoReflect.Descriptor instead.
func (*ExecuteVectorResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{25}
}

func (x *ExecuteVectorResponse) GetResults() []*VectorOperationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ExecuteVectorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteVectorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 单个向量操作结果 - 使用 oneof 区分
type VectorOperationResult struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Index   int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 对应 operations 中的索引
	Success bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*VectorOperationResult_InsertResult
	//	*VectorOperationResult_SearchResult
	//	*VectorOperationResult_DeleteResult
	//	*VectorOperationResult_UpsertResult
	Result        isVectorOperationResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorOperationResult) Reset() {
	*x = VectorOperationResult{}
	mi := &file_storage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorOperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorOperationResult) ProtoMessage() {}

func (x *VectorOperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorOperationResult.ProtoReflect.Descriptor instead.
func (*VectorOperationResult) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{26}
}

func (x *VectorOperationResult) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *VectorOperationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VectorOperationResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *VectorOperationResult) GetResult() isVectorOperationResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *VectorOperationResult) GetInsertResult() *VectorInsertResult {
	if x != nil {
		if x, ok := x.Result.(*VectorOperationResult_InsertResult); ok {
			return x.InsertResult
		}
	}
	return nil
}

func (x *VectorOperationResult) GetSearchResult() *VectorSearchResult {
	if x != nil {
		if x, ok := x.Result.(*VectorOperationResult_SearchResult); ok {
			return x.SearchResult
		}
	}
	return nil
}

func (x *VectorOperationResult) GetDeleteResult() *VectorDeleteResult {
	if x != nil {
		if x, ok := x.Result.(*VectorOperationResult_DeleteResult); ok {
			return x.DeleteResult
		}
	}
	return nil
}

func (x *VectorOperationResult) GetUpsertResult() *VectorUpsertResult {
	if x != nil {
		if x, ok := x.Result.(*VectorOperationResult_UpsertResult); ok {
			return x.UpsertResult
		}
	}
	return nil
}

type isVectorOperationResult_Result interface {
	isVectorOperationResult_Result()
}

type VectorOperationResult_InsertResult struct {
	InsertResult *VectorInsertResult `protobuf:"bytes,4,opt,name=insert_result,json=insertResult,proto3,oneof"`
}

type VectorOperationResult_SearchResult struct {
	SearchResult *VectorSearchResult `protobuf:"bytes,5,opt,name=search_result,json=searchResult,proto3,oneof"`
}

type VectorOperationResult_DeleteResult struct {
	DeleteResult *VectorDeleteResult `protobuf:"bytes,6,opt,name=delete_result,json=deleteResult,proto3,oneof"`
}

type VectorOperationResult_UpsertResult struct {
	UpsertResult *VectorUpsertResult `protobuf:"bytes,7,opt,name=upsert_result,json=upsertResult,proto3,oneof"`
}

func (*VectorOperationResult_InsertResult) isVectorOperationResult_Result() {}

func (*VectorOperationResult_SearchResult) isVectorOperationResult_Result() {}

func (*VectorOperationResult_DeleteResult) isVectorOperationResult_Result() {}

func (*VectorOperationResult_UpsertResult) isVectorOperationResult_Result() {}

// 向量插入结果
type VectorInsertResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InsertedCount int32                  `protobuf:"varint,1,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"` // 成功插入数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorInsertResult) Reset() {
	*x = VectorInsertResult{}
	mi := &file_storage_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorInsertResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorInsertResult) ProtoMessage() {}

func (x *VectorInsertResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorInsertResult.ProtoReflect.Descriptor instead.
func (*VectorInsertResult) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{27}
}

func (x *VectorInsertResult) GetInsertedCount() int32 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

// 向量更新或插入结果
type VectorUpsertResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpsertedCount int32                  `protobuf:"varint,1,opt,name=upserted_count,json=upsertedCount,proto3" json:"upserted_count,omitempty"` // 成功更新或插入数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorUpsertResult) Reset() {
	*x = VectorUpsertResult{}
	mi := &file_storage_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorUpsertResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorUpsertResult) ProtoMessage() {}

func (x *VectorUpsertResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorUpsertResult.ProtoReflect.Descriptor instead.
func (*VectorUpsertResult) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{28}
}

func (x *VectorUpsertResult) GetUpsertedCount() int32 {
	if x != nil {
		return x.UpsertedCount
	}
	return 0
}

// 向量搜索结果
type VectorSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*VectorMatch         `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"` // 匹配结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearchResult) Reset() {
	*x = VectorSearchResult{}
	mi := &file_storage_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchResult) ProtoMessage() {}

func (x *VectorSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchResult.ProtoReflect.Descriptor instead.
func (*VectorSearchResult) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{29}
}

func (x *VectorSearchResult) GetMatches() []*VectorMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

// 向量匹配项
type VectorMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // 向量 ID
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`                                                                               // 相似度得分
	Metadata      map[string]*TypedValue `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorMatch) Reset() {
	*x = VectorMatch{}
	mi := &file_storage_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorMatch) ProtoMessage() {}

func (x *VectorMatch) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorMatch.ProtoReflect.Descriptor instead.
func (*VectorMatch) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{30}
}

func (x *VectorMatch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VectorMatch) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *VectorMatch) GetMetadata() map[string]*TypedValue {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 向量删除结果
type VectorDeleteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"` // 成功删除数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorDeleteResult) Reset() {
	*x = VectorDeleteResult{}
	mi := &file_storage_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorDeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorDeleteResult) ProtoMessage() {}

func (x *VectorDeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorDeleteResult.ProtoReflect.Descriptor instead.
func (*VectorDeleteResult) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{31}
}

func (x *VectorDeleteResult) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\astorage\"\xa2\x02\n" +
	"\n" +
	"TypedValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValue\x12)\n" +
	"\x0ftimestamp_value\x18\x06 \x01(\x03H\x00R\x0etimestampValue\x123\n" +
	"\n" +
	"null_value\x18\a \x01(\x0e2\x12.storage.NullValueH\x00R\tnullValueB\a\n" +
	"\x05value\"m\n" +
	"\x0eExecuteRequest\x122\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x12.storage.OperationR\n" +
	"operations\x12'\n" +
	"\x0fuse_transaction\x18\x02 \x01(\bR\x0euseTransaction\"\x9a\x02\n" +
	"\tOperation\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x122\n" +
	"\x06insert\x18\x03 \x01(\v2\x18.storage.InsertOperationH\x00R\x06insert\x122\n" +
	"\x06update\x18\x04 \x01(\v2\x18.storage.UpdateOperationH\x00R\x06update\x122\n" +
	"\x06delete\x18\x05 \x01(\v2\x18.storage.DeleteOperationH\x00R\x06delete\x122\n" +
	"\x06select\x18\x06 \x01(\v2\x18.storage.SelectOperationH\x00R\x06selectB\v\n" +
	"\toperation\"9\n" +
	"\x0fInsertOperation\x12&\n" +
	"\x04rows\x18\x01 \x03(\v2\x12.storage.InsertRowR\x04rows\"\x93\x01\n" +
	"\tInsertRow\x126\n" +
	"\x06fields\x18\x01 \x03(\v2\x1e.storage.InsertRow.FieldsEntryR\x06fields\x1aN\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.storage.TypedValueR\x05value:\x028\x01\"\xac\x02\n" +
	"\x0fUpdateOperation\x12F\n" +
	"\n" +
	"set_fields\x18\x01 \x03(\v2'.storage.UpdateOperation.SetFieldsEntryR\tsetFields\x12*\n" +
	"\x05where\x18\x02 \x01(\v2\x14.storage.WhereClauseR\x05where\x12\x17\n" +
	"\araw_set\x18\x03 \x01(\tR\x06rawSet\x129\n" +
	"\x0eraw_set_params\x18\x04 \x03(\v2\x13.storage.TypedValueR\frawSetParams\x1aQ\n" +
	"\x0eSetFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.storage.TypedValueR\x05value:\x028\x01\"=\n" +
	"\x0fDeleteOperation\x12*\n" +
	"\x05where\x18\x01 \x01(\v2\x14.storage.WhereClauseR\x05where\"\xb7\x01\n" +
	"\x0fSelectOperation\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\x12*\n" +
	"\x05where\x18\x02 \x01(\v2\x14.storage.WhereClauseR\x05where\x12+\n" +
	"\border_by\x18\x03 \x01(\v2\x10.storage.OrderByR\aorderBy\x123\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x13.storage.PaginationR\n" +
	"pagination\"\xfa\x01\n" +
	"\vWhereClause\x12D\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2$.storage.WhereClause.ConditionsEntryR\n" +
	"conditions\x12\x1d\n" +
	"\n" +
	"raw_clause\x18\x02 \x01(\tR\trawClause\x122\n" +
	"\n" +
	"raw_params\x18\x03 \x03(\v2\x13.storage.TypedValueR\trawParams\x1aR\n" +
	"\x0fConditionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.storage.TypedValueR\x05value:\x028\x01\"?\n" +
	"\aOrderBy\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1e\n" +
	"\n" +
	"descending\x18\x02 \x01(\bR\n" +
	"descending\":\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"u\n" +
	"\x0fExecuteResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.storage.OperationResultR\aresults\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xd9\x02\n" +
	"\x0fOperationResult\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12<\n" +
	"\rinsert_result\x18\x04 \x01(\v2\x15.storage.InsertResultH\x00R\finsertResult\x12<\n" +
	"\rupdate_result\x18\x05 \x01(\v2\x15.storage.UpdateResultH\x00R\fupdateResult\x12<\n" +
	"\rdelete_result\x18\x06 \x01(\v2\x15.storage.DeleteResultH\x00R\fdeleteResult\x12<\n" +
	"\rselect_result\x18\a \x01(\v2\x15.storage.SelectResultH\x00R\fselectResultB\b\n" +
	"\x06result\"5\n" +
	"\fInsertResult\x12%\n" +
	"\x0einserted_count\x18\x01 \x01(\x05R\rinsertedCount\"3\n" +
	"\fUpdateResult\x12#\n" +
	"\raffected_rows\x18\x01 \x01(\x05R\faffectedRows\"3\n" +
	"\fDeleteResult\x12#\n" +
	"\raffected_rows\x18\x01 \x01(\x05R\faffectedRows\"L\n" +
	"\fSelectResult\x12&\n" +
	"\x04rows\x18\x01 \x03(\v2\x12.storage.ResultRowR\x04rows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x93\x01\n" +
	"\tResultRow\x126\n" +
	"\x06fields\x18\x01 \x03(\v2\x1e.storage.ResultRow.FieldsEntryR\x06fields\x1aN\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.storage.TypedValueR\x05value:\x028\x01\"P\n" +
	"\x14ExecuteVectorRequest\x128\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x18.storage.VectorOperationR\n" +
	"operations\"\xc4\x02\n" +
	"\x0fVectorOperation\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\tR\tpartition\x128\n" +
	"\x06insert\x18\x03 \x01(\v2\x1e.storage.VectorInsertOperationH\x00R\x06insert\x128\n" +
	"\x06search\x18\x04 \x01(\v2\x1e.storage.VectorSearchOperationH\x00R\x06search\x128\n" +
	"\x06delete\x18\x05 \x01(\v2\x1e.storage.VectorDeleteOperationH\x00R\x06delete\x128\n" +
	"\x06upsert\x18\x06 \x01(\v2\x1e.storage.VectorUpsertOperationH\x00R\x06upsertB\v\n" +
	"\toperation\"F\n" +
	"\x15VectorInsertOperation\x12-\n" +
	"\avectors\x18\x01 \x03(\v2\x13.storage.VectorDataR\avectors\"F\n" +
	"\x15VectorUpsertOperation\x12-\n" +
	"\avectors\x18\x01 \x03(\v2\x13.storage.VectorDataR\avectors\"\xc5\x01\n" +
	"\n" +
	"VectorData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12=\n" +
	"\bmetadata\x18\x03 \x03(\v2!.storage.VectorData.MetadataEntryR\bmetadata\x1aP\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.storage.TypedValueR\x05value:\x028\x01\"\xc6\x02\n" +
	"\x15VectorSearchOperation\x12!\n" +
	"\fquery_vector\x18\x01 \x03(\x02R\vqueryVector\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12\x1b\n" +
	"\tmin_score\x18\x03 \x01(\x02R\bminScore\x12B\n" +
	"\x06filter\x18\x04 \x03(\v2*.storage.VectorSearchOperation.FilterEntryR\x06filter\x12\x1f\n" +
	"\vfilter_expr\x18\x05 \x01(\tR\n" +
	"filterExpr\x12#\n" +
	"\routput_fields\x18\x06 \x03(\tR\foutputFields\x1aN\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.storage.TypedValueR\x05value:\x028\x01\"\xde\x01\n" +
	"\x15VectorDeleteOperation\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12B\n" +
	"\x06filter\x18\x02 \x03(\v2*.storage.VectorDeleteOperation.FilterEntryR\x06filter\x12\x1f\n" +
	"\vfilter_expr\x18\x03 \x01(\tR\n" +
	"filterExpr\x1aN\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.storage.TypedValueR\x05value:\x028\x01\"\x81\x01\n" +
	"\x15ExecuteVectorResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.storage.VectorOperationResultR\aresults\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xf7\x02\n" +
	"\x15VectorOperationResult\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12B\n" +
	"\rinsert_result\x18\x04 \x01(\v2\x1b.storage.VectorInsertResultH\x00R\finsertResult\x12B\n" +
	"\rsearch_result\x18\x05 \x01(\v2\x1b.storage.VectorSearchResultH\x00R\fsearchResult\x12B\n" +
	"\rdelete_result\x18\x06 \x01(\v2\x1b.storage.VectorDeleteResultH\x00R\fdeleteResult\x12B\n" +
	"\rupsert_result\x18\a \x01(\v2\x1b.storage.VectorUpsertResultH\x00R\fupsertResultB\b\n" +
	"\x06result\";\n" +
	"\x12VectorInsertResult\x12%\n" +
	"\x0einserted_count\x18\x01 \x01(\x05R\rinsertedCount\";\n" +
	"\x12VectorUpsertResult\x12%\n" +
	"\x0eupserted_count\x18\x01 \x01(\x05R\rupsertedCount\"D\n" +
	"\x12VectorSearchResult\x12.\n" +
	"\amatches\x18\x01 \x03(\v2\x14.storage.VectorMatchR\amatches\"\xc5\x01\n" +
	"\vVectorMatch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12>\n" +
	"\bmetadata\x18\x03 \x03(\v2\".storage.VectorMatch.MetadataEntryR\bmetadata\x1aP\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.storage.TypedValueR\x05value:\x028\x01\"9\n" +
	"\x12VectorDeleteResult\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount*\x1b\n" +
	"\tNullValue\x12\x0e\n" +
	"\n" +
	"NULL_VALUE\x10\x002\x9e\x01\n" +
	"\x0eStorageService\x12<\n" +
	"\aExecute\x12\x17.storage.ExecuteRequest\x1a\x18.storage.ExecuteResponse\x12N\n" +
	"\rExecuteVector\x12\x1d.storage.ExecuteVectorRequest\x1a\x1e.storage.ExecuteVectorResponseB\x1fZ\x1dbot_agent/gateway/internal/pbb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_storage_proto_goTypes = []any{
	(NullValue)(0),                // 0: storage.NullValue
	(*TypedValue)(nil),            // 1: storage.TypedValue
	(*ExecuteRequest)(nil),        // 2: storage.ExecuteRequest
	(*Operation)(nil),             // 3: storage.Operation
	(*InsertOperation)(nil),       // 4: storage.InsertOperation
	(*InsertRow)(nil),             // 5: storage.InsertRow
	(*UpdateOperation)(nil),       // 6: storage.UpdateOperation
	(*DeleteOperation)(nil),       // 7: storage.DeleteOperation
	(*SelectOperation)(nil),       // 8: storage.SelectOperation
	(*WhereClause)(nil),           // 9: storage.WhereClause
	(*OrderBy)(nil),               // 10: storage.OrderBy
	(*Pagination)(nil),            // 11: storage.Pagination
	(*ExecuteResponse)(nil),       // 12: storage.ExecuteResponse
	(*OperationResult)(nil),       // 13: storage.OperationResult
	(*InsertResult)(nil),          // 14: storage.InsertResult
	(*UpdateResult)(nil),          // 15: storage.UpdateResult
	(*DeleteResult)(nil),          // 16: storage.DeleteResult
	(*SelectResult)(nil),          // 17: storage.SelectResult
	(*ResultRow)(nil),             // 18: storage.ResultRow
	(*ExecuteVectorRequest)(nil),  // 19: storage.ExecuteVectorRequest
	(*VectorOperation)(nil),       // 20: storage.VectorOperation
	(*VectorInsertOperation)(nil), // 21: storage.VectorInsertOperation
	(*VectorUpsertOperation)(nil), // 22: storage.VectorUpsertOperation
	(*VectorData)(nil),            // 23: storage.VectorData
	(*VectorSearchOperation)(nil), // 24: storage.VectorSearchOperation
	(*VectorDeleteOperation)(nil), // 25: storage.VectorDeleteOperation
	(*ExecuteVectorResponse)(nil), // 26: storage.ExecuteVectorResponse
	(*VectorOperationResult)(nil), // 27: storage.VectorOperationResult
	(*VectorInsertResult)(nil),    // 28: storage.VectorInsertResult
	(*VectorUpsertResult)(nil),    // 29: storage.VectorUpsertResult
	(*VectorSearchResult)(nil),    // 30: storage.VectorSearchResult
	(*VectorMatch)(nil),           // 31: storage.VectorMatch
	(*VectorDeleteResult)(nil),    // 32: storage.VectorDeleteResult
	nil,                           // 33: storage.InsertRow.FieldsEntry
	nil,                           // 34: storage.UpdateOperation.SetFieldsEntry
	nil,                           // 35: storage.WhereClause.ConditionsEntry
	nil,                           // 36: storage.ResultRow.FieldsEntry
	nil,                           // 37: storage.VectorData.MetadataEntry
	nil,                           // 38: storage.VectorSearchOperation.FilterEntry
	nil,                           // 39: storage.VectorDeleteOperation.FilterEntry
	nil,                           // 40: storage.VectorMatch.MetadataEntry
}
var file_storage_proto_depIdxs = []int32{
	0,  // 0: storage.TypedValue.null_value:type_name -> storage.NullValue
	3,  // 1: storage.ExecuteRequest.operations:type_name -> storage.Operation
	4,  // 2: storage.Operation.insert:type_name -> storage.InsertOperation
	6,  // 3: storage.Operation.update:type_name -> storage.UpdateOperation
	7,  // 4: storage.Operation.delete:type_name -> storage.DeleteOperation
	8,  // 5: storage.Operation.select:type_name -> storage.SelectOperation
	5,  // 6: storage.InsertOperation.rows:type_name -> storage.InsertRow
	33, // 7: storage.InsertRow.fields:type_name -> storage.InsertRow.FieldsEntry
	34, // 8: storage.UpdateOperation.set_fields:type_name -> storage.UpdateOperation.SetFieldsEntry
	9,  // 9: storage.UpdateOperation.where:type_name -> storage.WhereClause
	1,  // 10: storage.UpdateOperation.raw_set_params:type_name -> storage.TypedValue
	9,  // 11: storage.DeleteOperation.where:type_name -> storage.WhereClause
	9,  // 12: storage.SelectOperation.where:type_name -> storage.WhereClause
	10, // 13: storage.SelectOperation.order_by:type_name -> storage.OrderBy
	11, // 14: storage.SelectOperation.pagination:type_name -> storage.Pagination
	35, // 15: storage.WhereClause.conditions:type_name -> storage.WhereClause.ConditionsEntry
	1,  // 16: storage.WhereClause.raw_params:type_name -> storage.TypedValue
	13, // 17: storage.ExecuteResponse.results:type_name -> storage.OperationResult
	14, // 18: storage.OperationResult.insert_result:type_name -> storage.InsertResult
	15, // 19: storage.OperationResult.update_result:type_name -> storage.UpdateResult
	16, // 20: storage.OperationResult.delete_result:type_name -> storage.DeleteResult
	17, // 21: storage.OperationResult.select_result:type_name -> storage.SelectResult
	18, // 22: storage.SelectResult.rows:type_name -> storage.ResultRow
	36, // 23: storage.ResultRow.fields:type_name -> storage.ResultRow.FieldsEntry
	20, // 24: storage.ExecuteVectorRequest.operations:type_name -> storage.VectorOperation
	21, // 25: storage.VectorOperation.insert:type_name -> storage.VectorInsertOperation
	24, // 26: storage.VectorOperation.search:type_name -> storage.VectorSearchOperation
	25, // 27: storage.VectorOperation.delete:type_name -> storage.VectorDeleteOperation
	22, // 28: storage.VectorOperation.upsert:type_name -> storage.VectorUpsertOperation
	23, // 29: storage.VectorInsertOperation.vectors:type_name -> storage.VectorData
	23, // 30: storage.VectorUpsertOperation.vectors:type_name -> storage.VectorData
	37, // 31: storage.VectorData.metadata:type_name -> storage.VectorData.MetadataEntry
	38, // 32: storage.VectorSearchOperation.filter:type_name -> storage.VectorSearchOperation.FilterEntry
	39, // 33: storage.VectorDeleteOperation.filter:type_name -> storage.VectorDeleteOperation.FilterEntry
	27, // 34: storage.ExecuteVectorResponse.results:type_name -> storage.VectorOperationResult
	28, // 35: storage.VectorOperationResult.insert_result:type_name -> storage.VectorInsertResult
	30, // 36: storage.VectorOperationResult.search_result:type_name -> storage.VectorSearchResult
	32, // 37: storage.VectorOperationResult.delete_result:type_name -> storage.VectorDeleteResult
	29, // 38: storage.VectorOperationResult.upsert_result:type_name -> storage.VectorUpsertResult
	31, // 39: storage.VectorSearchResult.matches:type_name -> storage.VectorMatch
	40, // 40: storage.VectorMatch.metadata:type_name -> storage.VectorMatch.MetadataEntry
	1,  // 41: storage.InsertRow.FieldsEntry.value:type_name -> storage.TypedValue
	1,  // 42: storage.UpdateOperation.SetFieldsEntry.value:type_name -> storage.TypedValue
	1,  // 43: storage.WhereClause.ConditionsEntry.value:type_name -> storage.TypedValue
	1,  // 44: storage.ResultRow.FieldsEntry.value:type_name -> storage.TypedValue
	1,  // 45: storage.VectorData.MetadataEntry.value:type_name -> storage.TypedValue
	1,  // 46: storage.VectorSearchOperation.FilterEntry.value:type_name -> storage.TypedValue
	1,  // 47: storage.VectorDeleteOperation.FilterEntry.value:type_name -> storage.TypedValue
	1,  // 48: storage.VectorMatch.MetadataEntry.value:type_name -> storage.TypedValue
	2,  // 49: storage.StorageService.Execute:input_type -> storage.ExecuteRequest
	19, // 50: storage.StorageService.ExecuteVector:input_type -> storage.ExecuteVectorRequest
	12, // 51: storage.StorageService.Execute:output_type -> storage.ExecuteResponse
	26, // 52: storage.StorageService.ExecuteVector:output_type -> storage.ExecuteVectorResponse
	51, // [51:53] is the sub-list for method output_type
	49, // [49:51] is the sub-list for method input_type
	49, // [49:49] is the sub-list for extension type_name
	49, // [49:49] is the sub-list for extension extendee
	0,  // [0:49] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	file_storage_proto_msgTypes[0].OneofWrappers = []any{
		(*TypedValue_StringValue)(nil),
		(*TypedValue_IntValue)(nil),
		(*TypedValue_DoubleValue)(nil),
		(*TypedValue_BoolValue)(nil),
		(*TypedValue_BytesValue)(nil),
		(*TypedValue_TimestampValue)(nil),
		(*TypedValue_NullValue)(nil),
	}
	file_storage_proto_msgTypes[2].OneofWrappers = []any{
		(*Operation_Insert)(nil),
		(*Operation_Update)(nil),
		(*Operation_Delete)(nil),
		(*Operation_Select)(nil),
	}
	file_storage_proto_msgTypes[12].OneofWrappers = []any{
		(*OperationResult_InsertResult)(nil),
		(*OperationResult_UpdateResult)(nil),
		(*OperationResult_DeleteResult)(nil),
		(*OperationResult_SelectResult)(nil),
	}
	file_storage_proto_msgTypes[19].OneofWrappers = []any{
		(*VectorOperation_Insert)(nil),
		(*VectorOperation_Search)(nil),
		(*VectorOperation_Delete)(nil),
		(*VectorOperation_Upsert)(nil),
	}
	file_storage_proto_msgTypes[26].OneofWrappers = []any{
		(*VectorOperationResult_InsertResult)(nil),
		(*VectorOperationResult_SearchResult)(nil),
		(*VectorOperationResult_DeleteResult)(nil),
		(*VectorOperationResult_UpsertResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		EnumInfos:         file_storage_proto_enumTypes,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
